---
# Snag configuartion

verbose: true

ignore:
  - .git
  - sample/_gomutate
  - "**.out"
  - gomutate
  # test in cmd/gomutate
  - cmd/gomutate/sub
  - cmd/gomutate/_sub

build:
  - go build ./cmd/gomutate
  - go vet .
  - gofmt -l -s .
  - golint .
  - go test . ./cmd/... ./mutants
