language: go

go:
  - 1.6
  - tip

before_install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/fzipp/gocyclo
  - go get github.com/mattn/goveralls

install:
  # make sure stuff actually builds
  - go build ./cmd/gomutate

script:
  # ensure everything is formatted all pretty like
  - gofmt -l -s .
  # vet out possible issues
  - go vet ./...
  # run tests
  - go test ./... -v -race

after_success:
  - |
    echo "mode: count" > profile.cov
    for dir in $(find . -maxdepth 10 -not -path 'vendor' -not -path './.git*' -not -path '*/_*' -type d);
    do
    if ls $dir/*.go &> /dev/null; then
      go test -short -covermode=count -coverprofile=$dir/profile.tmp $dir
      if [ -f $dir/profile.tmp ]
      then
        cat $dir/profile.tmp | tail -n +2 >> profile.cov
        rm $dir/profile.tmp
      fi
    fi
    done
    go tool cover -func profile.cov
    goveralls -coverprofile=profile.cov -service=travis-ci -repotoken=$COVERALLS -v

after_script:
  # check possible styling errors
  - golint ./...
  # check for potentially complex functions but don't fail build
  - gocyclo -over 15 . || true
  # refresh godocs in case there were api changes
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
      go list ./... | xargs -n 1 -I{} curl http://godoc.org/-/refresh -d path={}
    fi
